import json

content =  [ { "image_description": "A darkened room with a single spotlight shining on a person's face, with a determined expression and a hint of sweat on their forehead. They are looking up at something in the distance.", "text": "You've been pushing through the darkness" }, { "image_description": "A close-up shot of a person's hand holding a pen or pencil, with a notebook or journal open behind it. The paper is filled with scribbled notes and ideas.", "text": "And writing your own story" }, { "image_description": "An overhead view of a desk or workspace cluttered with papers, books, and other materials. A person's arm is reaching out to grab something from the top shelf.", "text": "Where every challenge becomes an opportunity for growth" }, { "image_description": "A montage of people from different backgrounds and cultures working together, laughing, and high-fiving each other. The camera pans out to show a cityscape or a global map in the background.", "text": "And success is not just about achieving your goals, but also about inspiring others along the way" }, { "image_description": "A close-up shot of a person's face, with a huge smile and tears of joy in their eyes. They are holding a certificate or medal, with confetti and balloons surrounding them.", "text": "So take a moment to celebrate your victories" }, { "image_description": "A wide-angle shot of a person standing on a mountaintop or a cliff, looking out at a breathtaking view. The sun is setting behind them, casting a warm glow over the scene.", "text": "And remember that the greatest achievements are not just about what you've accomplished, but also about who you've become in the process" }, { "image_description": "A split-screen image showing a person's face on one side and their goals or vision board on the other. The text 'You Got This' is written across the screen in bold letters.", "text": "So keep pushing forward, stay focused, and know that you have what it takes to achieve greatness" } ]
output = content #json.loads(content)
print(output)
image_prompts = [k['image_description'] for k in output]
texts = [k['text'] for k in output]

print("image_prompts: ", image_prompts)
print("texts: ", texts)